// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using csharp_boolflix.DataBase;

#nullable disable

namespace csharp_boolflix.Migrations
{
    [DbContext(typeof(BoolflixContext))]
    [Migration("20220802100458_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("csharp_boolflix.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("csharp_boolflix.Models.PlayedHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("PlayedHistories");
                });

            modelBuilder.Entity("csharp_boolflix.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("csharp_boolflix.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsChild")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayedHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayedHistoryId")
                        .IsUnique();

                    b.HasIndex("PlaylistId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("csharp_boolflix.Models.VideoContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("PlayedHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayedHistoryId");

                    b.HasIndex("ProfileId");

                    b.ToTable("VideoContents");

                    b.HasDiscriminator<string>("Discriminator").HasValue("VideoContent");
                });

            modelBuilder.Entity("GenreVideoContent", b =>
                {
                    b.Property<int>("GenresListId")
                        .HasColumnType("int");

                    b.Property<int>("VideoContentsId")
                        .HasColumnType("int");

                    b.HasKey("GenresListId", "VideoContentsId");

                    b.HasIndex("VideoContentsId");

                    b.ToTable("GenreVideoContent");
                });

            modelBuilder.Entity("PlaylistVideoContent", b =>
                {
                    b.Property<int>("PlaylistsListId")
                        .HasColumnType("int");

                    b.Property<int>("VideoContentsId")
                        .HasColumnType("int");

                    b.HasKey("PlaylistsListId", "VideoContentsId");

                    b.HasIndex("VideoContentsId");

                    b.ToTable("PlaylistVideoContent");
                });

            modelBuilder.Entity("csharp_boolflix.Models.Film", b =>
                {
                    b.HasBaseType("csharp_boolflix.Models.VideoContent");

                    b.HasDiscriminator().HasValue("Film");
                });

            modelBuilder.Entity("csharp_boolflix.Models.Profile", b =>
                {
                    b.HasOne("csharp_boolflix.Models.PlayedHistory", "HistoryList")
                        .WithOne("Profile")
                        .HasForeignKey("csharp_boolflix.Models.Profile", "PlayedHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("csharp_boolflix.Models.Playlist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoryList");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("csharp_boolflix.Models.VideoContent", b =>
                {
                    b.HasOne("csharp_boolflix.Models.PlayedHistory", null)
                        .WithMany("VideoContents")
                        .HasForeignKey("PlayedHistoryId");

                    b.HasOne("csharp_boolflix.Models.Profile", null)
                        .WithMany("PreferredList")
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("GenreVideoContent", b =>
                {
                    b.HasOne("csharp_boolflix.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("csharp_boolflix.Models.VideoContent", null)
                        .WithMany()
                        .HasForeignKey("VideoContentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlaylistVideoContent", b =>
                {
                    b.HasOne("csharp_boolflix.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("csharp_boolflix.Models.VideoContent", null)
                        .WithMany()
                        .HasForeignKey("VideoContentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("csharp_boolflix.Models.PlayedHistory", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("VideoContents");
                });

            modelBuilder.Entity("csharp_boolflix.Models.Profile", b =>
                {
                    b.Navigation("PreferredList");
                });
#pragma warning restore 612, 618
        }
    }
}
